name: Build-Orbis-Pro-APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK
        uses: duckduckgo/gh-action-website-to-apk@v1
        with:
          url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          name: "Orbis_Ultra_Pro"
